// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6_IdMJq5kyVtcq4cMVbPPm-nq8kSFWzY',
    appId: '1:380349437064:web:e4a23e01cc57e124ab7b3d',
    messagingSenderId: '380349437064',
    projectId: 'phone-auth-d36db',
    authDomain: 'phone-auth-d36db.firebaseapp.com',
    storageBucket: 'phone-auth-d36db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWazlQORVZyq4ex9BGNm6HVPlDkn4ZTk',
    appId: '1:380349437064:android:bdace10c1af66dbaab7b3d',
    messagingSenderId: '380349437064',
    projectId: 'phone-auth-d36db',
    storageBucket: 'phone-auth-d36db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr_wtsBZxki2ZkKq18bdmtQXLqQhqMU3Y',
    appId: '1:380349437064:ios:49f441cdddab79cfab7b3d',
    messagingSenderId: '380349437064',
    projectId: 'phone-auth-d36db',
    storageBucket: 'phone-auth-d36db.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr_wtsBZxki2ZkKq18bdmtQXLqQhqMU3Y',
    appId: '1:380349437064:ios:180ce52da04987f8ab7b3d',
    messagingSenderId: '380349437064',
    projectId: 'phone-auth-d36db',
    storageBucket: 'phone-auth-d36db.appspot.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
